"use client";

import { useCallback, useEffect, useState } from "react";
import { t } from "../../lib/i18n";
import { useLocale } from "../../lib/locale-context";
import { api } from "../../lib/api";
import { homeworkStatusLabel, homeworkStatusPill } from "../../lib/format";
import type { Homework, Page, Settings } from "../../lib/types";
import { DateField } from "../date-field";
import { Icon } from "../icon";
import { SearchField } from "../search-field";
import { Select } from "../select-field";
import { Empty, Notice, PageTitle } from "../ui";

export function HomeworkView() {
  const [items, setItems] = useState<Homework[]>([]); const [counts, setCounts] = useState<Record<string, number>>({}); const [status, setStatus] = useState("alle"); const [query, setQuery] = useState(""); const [since, setSince] = useState("2000-01-01"); const [includeTests, setIncludeTests] = useState(false); const [error, setError] = useState("");
  const load = useCallback(async () => { try { const params = new URLSearchParams({ status, q: query, since, limit: "200", include_tests: includeTests ? "1" : "0" }); const response = await api<Page<Homework>>(`/homework?${params}`); setItems(response.items); setCounts(response.counts ?? {}); setError(""); } catch (e) { setError((e as Error).message); } }, [status, query, since, includeTests]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { void api<Settings>("/settings").then((result) => { if (typeof result.values.hw_status === "string") setStatus(result.values.hw_status); if (typeof result.values.hw_tests === "boolean") setIncludeTests(result.values.hw_tests); }).catch(() => undefined); }, []);
  async function change(task: Homework, operation: "done" | "trash") { try { await api(`/homework/${task.id}/${operation}`, { method: "POST", body: JSON.stringify(operation === "done" ? { done: !task.is_done } : { hide: !task.is_hidden }) }); await load(); } catch (e) { setError((e as Error).message); } }
  const visibleLabel = status === "papierkorb" ? t("homework.trashLabel") : status === "alle" ? t("homework.entriesLabel") : homeworkStatusLabel(status);
  return <><PageTitle eyebrow={t("homework.eyebrow")} title={t("nav.homework")} detail={t("homework.detail")} /><Notice error={error} />
    <section className="stat-grid"><div className="stat"><div className="n">{items.length}</div><div className="l">{t("homework.loaded")}</div></div><div className="stat"><div className="n">{counts.offen ?? 0}</div><div className="l">{t("homework.open")}</div></div><div className="stat"><div className="n n-danger">{counts.ueberfaellig ?? 0}</div><div className="l">{t("homework.overdue")}</div></div><div className="stat"><div className="n n-ok">{counts.erledigt ?? 0}</div><div className="l">{t("homework.done")}</div></div></section>
    <div className="layout homework-layout"><aside className="sidebar"><h2>{t("homework.filterTitle")}</h2><div className="field"><label htmlFor="hw-search">{t("homework.searchLabel")}</label><SearchField className="input-pill" ariaLabel={t("homework.searchPlaceholder")} placeholder={t("homework.searchPlaceholder")} value={query} onChange={setQuery} /></div><div className="field"><label id="hw-status-label">{t("homework.statusLabel")}</label><Select labelledBy="hw-status-label" value={status} onChange={setStatus} options={[{ value: "alle", label: t("overview.allTasks") }, { value: "offen", label: t("homework.statusOpen") }, { value: "überfällig", label: t("homework.statusOverdue") }, { value: "erledigt", label: t("homework.statusDone") }, { value: "papierkorb", label: t("homework.trashWithCount", { count: counts.papierkorb ?? 0 }) }]} /></div><div className="field"><label htmlFor="hw-since">{t("messages.sinceLabel")}</label><DateField ariaLabel={t("messages.sinceLabel")} value={since} onChange={setSince} /></div><label className="check"><input type="checkbox" checked={includeTests} onChange={(event) => setIncludeTests(event.target.checked)} /> {t("homework.includeTests")}</label><button className="btn btn-primary" type="button" onClick={() => void load()}><Icon name="refresh" />{t("homework.reload")}</button>{(counts.papierkorb ?? 0) > 0 && <button className="btn btn-light" type="button" onClick={() => setStatus("papierkorb")}><Icon name="trash" />{t("homework.trashWithCount", { count: counts.papierkorb })}</button>}</aside>
      <div className="feed"><div className="feed-head"><p className="stats">{t("homework.shownCount", { count: items.length, label: visibleLabel })}</p><p className="swipe-hint">{t("homework.swipeHint")}</p></div><div id="list">{items.map((task) => <article className={`hw card ${task.status === "überfällig" ? "st-ueber" : task.status === "heute fällig" ? "st-heute" : task.is_done ? "st-erledigt" : "st-offen"}${task.is_done ? " is-done" : ""}${task.is_hidden ? " is-hidden" : ""}`} key={task.id}><h3>{task.title}</h3><div className="meta"><span className="tag tag-muted">{task.type_label ?? task.type}</span><span className="tag tag-blue">{homeworkStatusPill(task.status)}</span>{task.is_hidden && <span className="tag tag-gray">{t("homework.deleted")}</span>}<span>{t("homework.dueLabel")} <strong>{task.due_display}</strong></span><span>{t("homework.assignedLabel")} {task.assigned ?? task.assigned_iso ?? "–"}</span>{task.subject && <span>{task.subject}</span>}<span>{task.teacher || task.author || ""}</span>{task.is_starred && <span className="tag tag-soft">{t("homework.starred")}</span>}{task.done_at && <span className="tag tag-soft">✓ {task.done_at}</span>}</div><div className="text">{task.description?.trim() || t("common.noDescription")}</div><div className="hw-actions"><button className={`btn ${task.is_done ? "btn-light" : "btn-primary"} btn-sm`} type="button" onClick={() => void change(task, task.is_hidden ? "trash" : "done")}><Icon name={task.is_hidden ? "restore" : "check"} />{task.is_hidden ? t("homework.restore") : task.is_done ? t("homework.reopen") : t("homework.doneBtn")}</button>{!task.is_hidden && <button className="btn btn-light btn-sm" type="button" onClick={() => void change(task, "trash")}><Icon name="trash" />{t("homework.trashLabel")}</button>}</div></article>)}</div>{!items.length && <Empty>{status === "papierkorb" ? t("homework.trashEmpty") : t("homework.empty")}</Empty>}</div></div>
  </>;
}
