"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { localeTag, t } from "../../lib/i18n";
import { useLocale } from "../../lib/locale-context";
import { api } from "../../lib/api";
import { formatDate, messageAttachments } from "../../lib/format";
import type { Message, Page, Recipient, Thread } from "../../lib/types";
import { DateField } from "../date-field";
import { Icon } from "../icon";
import { SearchField } from "../search-field";
import { Select } from "../select-field";
import { Empty, Notice, PageTitle } from "../ui";

export function MessagesView() {
  useLocale(); // abonniert den Sprachwechsel, damit alle t()-Texte neu rendern
  const [items, setItems] = useState<Message[]>([]); const [q, setQ] = useState(""); const [type, setType] = useState(""); const [since, setSince] = useState("2000-01-01"); const [selected, setSelected] = useState<Message | null>(null); const [composeOpen, setComposeOpen] = useState(false); const [thread, setThread] = useState<Thread | null>(null); const [recipients, setRecipients] = useState<Recipient[]>([]); const [recipientQuery, setRecipientQuery] = useState(""); const [error, setError] = useState(""); const [feedback, setFeedback] = useState(""); const [page, setPage] = useState(0); const [refreshing, setRefreshing] = useState(false);
  const load = useCallback(async (refresh = false) => {
    setRefreshing(refresh);
    try { const params = new URLSearchParams({ limit: "20", offset: String(page * 20), since }); if (q) params.set("q", q); if (type) params.set("type", type); if (refresh) params.set("refresh", "1"); const result = await api<Page<Message>>(`/messages?${params}`); setItems(result.items); setError(""); }
    catch (e) { setError((e as Error).message); } finally { setRefreshing(false); }
  }, [page, q, since, type]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { void api<{ items: Recipient[] }>("/recipients").then((r) => setRecipients(r.items)).catch(() => undefined); }, []);
  async function openThread(message: Message) { setComposeOpen(false); setSelected(message); setThread(await api<Thread>(`/messages/${message.id}/thread`).catch((e: Error) => { setError(e.message); return null; })); }
  async function send(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); const recipientsValue = form.getAll("recipients").map(String); try { await api("/messages/send", { method: "POST", body: JSON.stringify({ recipients: recipientsValue, body: String(form.get("body") ?? "") }) }); setFeedback(t("messages.sentMessage")); formElement.reset(); setRecipientQuery(""); await load(true); } catch (e) { setError((e as Error).message); } }
  async function reply(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!selected) return; const formElement = event.currentTarget; const form = new FormData(formElement); try { await api(`/messages/${selected.id}/reply`, { method: "POST", body: JSON.stringify({ body: String(form.get("body") ?? "") }) }); setFeedback(t("messages.sentReply")); await openThread(selected); formElement.reset(); } catch (e) { setError((e as Error).message); } }
  async function markRead() { try { const result = await api<{ marked: number }>("/messages/read", { method: "POST" }); setFeedback(t("messages.markedRead", { marked: result.marked })); await load(); } catch (e) { setError((e as Error).message); } }
  async function download(message: Message, idx: number, name: string) { try { const grant = await api<{ download_token: string }>("/messages/download-token", { method: "POST", body: JSON.stringify({ event_id: message.id, idx }) }); const response = await fetch(`/api/v1/messages/${message.id}/attachments/${idx}?dl=${encodeURIComponent(grant.download_token)}`); if (!response.ok) throw new Error(t("messages.attachFailed")); const blob = await response.blob(); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = name; a.click(); URL.revokeObjectURL(url); } catch (e) { setError((e as Error).message); } }
  const filteredRecipients = recipients.filter((recipient) => !recipientQuery || `${recipient.name} ${recipient.kind ?? ""} ${recipient.detail ?? ""}`.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLocaleLowerCase(localeTag()).includes(recipientQuery.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLocaleLowerCase(localeTag())));
  return <><PageTitle eyebrow={t("messages.eyebrow")} title={t("nav.messages")} detail={t("messages.detail")} /><Notice error={error} /><p className="notice-success" aria-live="polite">{feedback}</p>
    <section className="two-column"><div className="panel"><div className="panel-heading"><h2>{t("nav.messages")}</h2><div className="message-actions"><button className="secondary" type="button" onClick={() => void markRead()}><Icon name="check" />{t("messages.markAllRead")}</button><button className="primary" type="button" onClick={() => { setSelected(null); setThread(null); setComposeOpen(true); }}>{t("messages.new")}</button></div></div>
      <div className="filters"><SearchField ariaLabel={t("messages.searchAria")} placeholder={t("messages.searchPlaceholder")} value={q} onChange={(next) => { setPage(0); setQ(next); }} /><Select className="filter-select" ariaLabel={t("messages.typeAria")} value={type} onChange={(next) => { setPage(0); setType(next); }} options={[{ value: "", label: t("messages.allTypes") }, { value: "sprava", label: t("nav.messages") }, { value: "news", label: t("messages.typeNews") }, { value: "anketa", label: t("messages.typePolls") }, { value: "chat", label: t("messages.typeChats") }, { value: "genotif", label: t("messages.typeNotices") }]} /><label className="since-filter">{t("messages.sinceLabel")}<DateField ariaLabel={t("messages.sinceLabel")} value={since} onChange={(next) => { setPage(0); setSince(next); }} /></label><button className="secondary" type="button" disabled={refreshing} onClick={() => void load(true)}>{refreshing ? t("common.loading") : t("homework.reload")}</button></div>
      {items.map((message) => { const attachments = messageAttachments(message); return <button className={`message-row ${selected?.id === message.id ? "selected" : ""}`} key={message.id} onClick={() => void openThread(message)}><span className="message-meta"><strong>{message.author || t("common.school")}</strong><small>{message.timestamp || formatDate(message.timestamp_iso)}</small></span><span className="row-snippet">{message.text || t("common.noText")}</span><span className="message-tags">{message.type !== "sprava" && <span className="tag tag-muted">{message.type_label}</span>}{message.is_starred && <span className="tag tag-soft">{t("messages.starred")}</span>}{message.is_done && <span className="tag tag-soft">{t("messages.done")}</span>}{message.reaction_count > 0 && <span className="tag tag-soft">♥ {message.reaction_count}</span>}{attachments.length > 0 && <span className="tag tag-blue">{attachments.length} {attachments.length === 1 ? t("messages.fileOne") : t("messages.fileMany")}</span>}</span></button>; })}
      {!items.length && <Empty>{t("messages.empty")}</Empty>}<div className="pager"><button className="secondary" disabled={page === 0} onClick={() => setPage((p) => Math.max(0, p - 1))}><Icon name="left" />{t("messages.back")}</button><span>{t("messages.page", { n: page + 1 })}</span><button className="secondary" disabled={items.length < 20} onClick={() => setPage((p) => p + 1)}>{t("messages.next")}<Icon name="right" /></button></div></div>
      <div className="panel"><div className="panel-heading"><h2>{selected ? t("messages.messageLabel") : composeOpen ? t("messages.newMessage") : t("nav.messages")}</h2>{selected && <button className="secondary" onClick={() => { setSelected(null); setThread(null); setComposeOpen(true); }}>{t("messages.newMessage")}</button>}{!selected && composeOpen && <button className="secondary" onClick={() => setComposeOpen(false)}><Icon name="close" />{t("common.close")}</button>}</div>
        {selected ? <><div className="message-detail"><p className="muted">{selected.timestamp || formatDate(selected.timestamp_iso)} · {selected.type_label}</p><p><strong>{selected.author}</strong>{selected.recipient && <> → {selected.recipient}</>}</p><p>{selected.text || t("common.noText")}</p>{messageAttachments(selected).map((name, idx) => <button className="secondary attachment-button" key={`${name}-${idx}`} onClick={() => void download(selected, idx, name)}><Icon name="download" />{t("messages.loadFile", { name })}</button>)}</div>{thread && <><h3>{t("messages.conversation")}</h3>{thread.likes.map((like, i) => <p className="muted" key={`${like.name}-${i}`}>{t("messages.liked", { name: like.name, date: like.date })}</p>)}{thread.replies.map((reply, i) => <div className="reply" key={`${reply.name}-${i}`}><strong>{reply.name}</strong><p>{reply.text}</p></div>)}<form className="stack-form" onSubmit={reply}><label>{t("messages.replyLabel")}<textarea name="body" required rows={4} maxLength={5000} /></label><button className="primary"><Icon name="send" />{t("messages.sendReply")}</button></form></>}</> : composeOpen ? <form className="stack-form" onSubmit={send}><label>{t("messages.recipientSearch")}<input aria-label={t("messages.recipientSearch")} placeholder={t("messages.recipientPlaceholder")} value={recipientQuery} onChange={(e) => setRecipientQuery(e.target.value)} /></label><label>{t("messages.recipients")}</label><div className="recipient-list">{filteredRecipients.map((recipient) => <label className="check" key={recipient.id}><input type="checkbox" name="recipients" value={recipient.id} /> {recipient.name}{recipient.kind && <span className="tag tag-muted">{recipient.kind === "teacher" ? t("grades.colTeacher") : t("messages.roleStudent")}</span>}</label>)}{!filteredRecipients.length && <p className="muted">{t("messages.noRecipients")}</p>}</div><small>{t("messages.multipleHint")}</small><label>{t("messages.messageLabel")}<textarea name="body" required rows={8} maxLength={5000} placeholder={t("messages.messagePlaceholder")} /></label><button className="primary"><Icon name="send" />{t("messages.sendMessage")}</button></form> : <div className="detail-empty"><p><strong>{t("messages.noSelection")}</strong></p><p className="muted">{t("messages.selectHint")}</p><button className="btn btn-primary btn-sm" onClick={() => setComposeOpen(true)}><Icon name="pencil" />{t("messages.newMessageBtn")}</button></div>}</div></section></>;
}
