"use client";

import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { localeTag, t } from "../../lib/i18n";
import { useLocale } from "../../lib/locale-context";
import { normalizeHidden, normalizeOrder, normalizeSpans, SECTION_KEYS, serializeSpans, spanOf, type SectionState } from "../../lib/section-layout";
import { api } from "../../lib/api";
import { homeworkStatusPill, lessonStartIndex, weatherIcon } from "../../lib/format";
import type { Homework, Lesson, Message, Page, Settings, Weather } from "../../lib/types";
import { Icon } from "../icon";
import { SectionBar } from "../section-bar";
import { Empty, Notice } from "../ui";

export function OverviewView({ username }: { username: string }) {
  useLocale(); // abonniert den Sprachwechsel, damit alle t()-Texte neu rendern
  const [messages, setMessages] = useState<Message[]>([]); const [homework, setHomework] = useState<Homework[]>([]); const [counts, setCounts] = useState<Record<string, number>>({}); const [lessons, setLessons] = useState<Lesson[]>([]); const [weather, setWeather] = useState<Weather | null>(null); const [settings, setSettings] = useState<Settings | null>(null); const [error, setError] = useState(""); const [clock, setClock] = useState<Date | null>(null); const [lessonIndex, setLessonIndex] = useState(0); const [loaded, setLoaded] = useState(false);
  const slotRefs = useRef<Record<string, HTMLDivElement | null>>({});
  const [editing, setEditing] = useState(false); const [order, setOrder] = useState<string[]>(SECTION_KEYS.slice()); const [hidden, setHidden] = useState<string[]>([]); const [spans, setSpans] = useState<Record<string, number>>({}); const [saving, setSaving] = useState(false); const [saved, setSaved] = useState(false);
  useEffect(() => { const tick = () => setClock(new Date()); tick(); const timer = window.setInterval(tick, 1000); return () => window.clearInterval(timer); }, []);
  useEffect(() => { let live = true; Promise.all([api<Page<Message>>("/messages?limit=4"), api<Page<Homework>>("/homework?limit=5&status=offen"), api<{ lessons: Lesson[] }>("/timetable/day"), api<Weather>("/wetter?city=Berlin"), api<Settings>("/settings")]).then(([m, h, t, w, s]) => { if (!live) return; setMessages(m.items); setHomework(h.items); setCounts(h.counts ?? {}); const schoolDayLessons = t.lessons.filter((lesson) => !lesson.is_event); setLessons(schoolDayLessons); setLessonIndex(lessonStartIndex(schoolDayLessons, new Date())); setWeather(w); setSettings(s); setOrder(normalizeOrder(s.values)); setHidden(normalizeHidden(s.values)); setSpans(normalizeSpans(s.values)); }).catch((e: Error) => { if (live) setError(e.message); }).finally(() => { if (live) setLoaded(true); }); return () => { live = false; }; }, []);
  const schoolLessons = lessons.filter((lesson) => !lesson.is_event); const selectedLesson = schoolLessons[Math.min(lessonIndex, Math.max(schoolLessons.length - 1, 0))]; const layout: SectionState = { order, hidden, spans }; const visibleOrder = order.filter((key) => !hidden.includes(key));
  const sectionLabels: Record<string, string> = { messages: t("nav.messages"), homework: t("nav.homework"), weather: t("overview.weather") };
  const sectionHints = { drag: t("overview.editorDrag"), up: t("settings.moveUp"), down: t("settings.moveDown"), hide: t("overview.editorHide"), show: t("overview.editorShow"), hidden: t("overview.editorHidden"), wide: t("overview.editorWide"), narrow: t("overview.editorNarrow") };
  async function saveLayout(next: SectionState) {
    setOrder(next.order); setHidden(next.hidden); setSpans(next.spans); setSaving(true);
    const body = { ov_order: next.order.join(","), ov_hidden: next.hidden.join(","), ov_span: serializeSpans(next.spans, next.order) };
    try { const result = await api<{ values: Record<string, unknown> }>("/settings", { method: "PUT", body: JSON.stringify(body) }); setSettings((current) => (current ? { ...current, values: { ...current.values, ...result.values } } : current)); setSaved(true); window.setTimeout(() => setSaved(false), 1600); }
    catch (e) { setError((e as Error).message); }
    finally { setSaving(false); }
  }
  function resetLayout() { void saveLayout({ order: SECTION_KEYS.slice(), hidden: [], spans: {} }); }
  const sections: Record<string, React.ReactNode> = {
    homework: <section className="ov-col anim-in" style={{ "--d": "80ms" } as React.CSSProperties} key="homework"><div className="ov-col-head"><h2>{t("nav.homework")}</h2><div className="ov-actions"><Link className="btn btn-primary btn-sm" href="/homework"><Icon name="list" />{t("overview.allTasks")}</Link></div></div><div className="ov-bundle card"><span><strong>{counts.offen ?? 0}</strong> {t("homework.open")}</span><span className="sep">·</span><span><strong className="n-danger">{counts.ueberfaellig ?? 0}</strong> {t("homework.overdue")}</span><span className="sep">·</span><span><strong className="n-ok">{counts.erledigt ?? 0}</strong> {t("homework.done")}</span></div>{homework.slice(0, 5).map((task) => <article className={`hw card ${task.status === "überfällig" ? "st-ueber" : task.status === "heute fällig" ? "st-heute" : task.is_done ? "st-erledigt" : "st-offen"} ${task.is_done ? "is-done" : ""}`} key={task.id}><h3>{task.title}</h3><div className="meta"><span className="tag tag-muted">{task.subject}</span><span className="tag tag-blue">{homeworkStatusPill(task.status)}</span><span>{t("homework.dueLabel")} <strong>{task.due_display}</strong></span><span>{task.teacher}</span></div><div className="text">{task.description || t("common.noDescription")}</div></article>)}{!homework.length && <Empty>{t("overview.emptyHomework")}</Empty>}</section>,
    messages: <section className="ov-col anim-in" style={{ "--d": "80ms" } as React.CSSProperties} key="messages"><div className="ov-col-head"><h2>{t("nav.messages")} <span className="muted">· {t("overview.newMessages", { count: messages.length })}</span></h2><div className="ov-actions"><Link className="btn btn-light btn-sm" href="/messages"><Icon name="list" />{t("overview.allMessages")}</Link></div></div>{messages.map((message) => <article className="card overview-message" key={message.id}><div className="meta"><strong>{message.author || t("common.school")}</strong><span>{message.timestamp}</span></div><div className="text">{message.text || message.type_label}</div></article>)}{!messages.length && <Empty>{t("overview.emptyMessages")}</Empty>}</section>,
    weather: settings?.values.ov_wetter === false ? null : <section className="ov-col anim-in" style={{ "--d": "60ms" } as React.CSSProperties} key="weather"><div className="ov-col-head"><h2>{t("overview.weather")}</h2></div>{weather ? <div className="weather-card"><div className="wx-summary"><span className="wx-summary-title">{t("overview.weather")}</span><span className="wx-summary-city">{weather.city}</span></div><div className="wx-forecast">{[[t("overview.today"), weather.today.temp, weather.today.min, weather.today.max, weather.today.desc, weather.today.icon], [t("overview.tomorrow"), null, weather.tomorrow.min, weather.tomorrow.max, weather.tomorrow.desc, weather.tomorrow.icon], [t("overview.dayAfter"), null, weather.day3.min, weather.day3.max, weather.day3.desc, weather.day3.icon]].map(([label, temp, min, max, desc, icon]) => <div className="wx-day" key={String(label)}><span className="wx-l">{label}</span><span className="wx-img" aria-hidden="true">{weatherIcon(desc, typeof icon === "string" ? icon : undefined)}</span><strong className="wx-temp">{temp == null ? `${max}°` : `${temp}°`}</strong><span className="wx-cond">{desc}</span><span className="wx-range">{min}° – {max}°</span></div>)}</div></div> : <div className="weather-card"><div className="wx-unavailable"><span className="wx-unavailable-mark">☼</span><span><strong>{t("overview.weatherUnavailable")}</strong><small>{t("overview.weatherHint")}</small></span></div></div>}</section>,
  };
  return <><div className="ov-top anim-in"><div className="clock-card"><div className="clock-time">{clock?.toLocaleTimeString(localeTag(), { hour: "2-digit", minute: "2-digit", second: "2-digit", hour12: settings?.values?.time_format === "12h" }) ?? "--:--:--"}</div><div className="clock-date">{clock?.toLocaleDateString(localeTag(), { weekday: "long", day: "numeric", month: "long" }) ?? ""}</div></div><div className="now-card now-right"><div className="now-top"><span className="l">{t("overview.lessonsToday")}</span><span className="now-count">{schoolLessons.length > 1 ? `${Math.min(lessonIndex + 1, schoolLessons.length)} / ${schoolLessons.length}` : ""}</span></div>{selectedLesson ? <><div className="n">{selectedLesson.title}</div><div className="s">{t("timetable.lessonHour", { lesson: selectedLesson.period })} · {selectedLesson.time}{selectedLesson.rooms ? ` · ${t("overview.room", { rooms: selectedLesson.rooms })}` : ""}{selectedLesson.teachers ? ` · ${selectedLesson.teachers}` : ""}</div><div className="now-tags">{selectedLesson.is_cancelled && <span className="tag tag-muted">{t("overview.cancelled")}</span>}{selectedLesson.is_online && <span className="tag tag-soft">{t("overview.online")}</span>}</div></> : loaded ? <><div className="n">{t("overview.free")}</div><div className="s">{t("overview.noLessonsToday")}</div></> : <><div className="n">{t("overview.loading")}</div><div className="s">{t("overview.loadingTimetable")}</div></>}<div className="now-nav"><button className="now-arrow" aria-label={t("overview.prevLesson")} onClick={() => setLessonIndex((i) => Math.max(0, i - 1))}>‹</button><Link className="now-link" href="/timetable">{t("nav.timetable")}</Link><button className="now-arrow" aria-label={t("overview.nextLesson")} onClick={() => setLessonIndex((i) => Math.min(schoolLessons.length - 1, i + 1))}>›</button></div></div></div><Notice error={error} /><div className="ov-toolbar">
    <button type="button" className={`btn btn-sm ${editing ? "btn-primary" : "btn-light"}`} aria-pressed={editing} onClick={() => setEditing((value) => !value)}><Icon name="pencil" />{editing ? t("overview.editorDone") : t("overview.editorToggle")}</button>
    {editing && <button type="button" className="btn btn-light btn-sm" onClick={resetLayout}><Icon name="refresh" />{t("overview.editorReset")}</button>}
    <span className="ov-toolbar-status" aria-live="polite">{editing ? (saving ? t("overview.editorSaving") : t("overview.editorHint")) : saved ? t("overview.editorSaved") : ""}</span>
  </div>
  {loaded && !visibleOrder.length && editing && <p className="sec-warn">{t("overview.editorEmpty")}</p>}
  <div className={`ov-grid${editing ? " is-editing" : ""}`}>{(editing ? order : visibleOrder).map((key) => <div className="ov-slot" key={key} style={{ "--span": spanOf(spans, key) } as React.CSSProperties} ref={(element) => { slotRefs.current[key] = element; }}>
    {editing && <SectionBar sectionKey={key} label={sectionLabels[key] ?? key} state={layout} index={order.indexOf(key)} total={order.length} hints={sectionHints} measure={() => order.map((entry) => slotRefs.current[entry]?.getBoundingClientRect()).filter((rect): rect is DOMRect => Boolean(rect)).map((rect) => ({ top: rect.top, bottom: rect.bottom }))} onChange={(next) => void saveLayout(next)} />}
    {!hidden.includes(key) && sections[key]}
  </div>)}</div></>;
}
