"use client";

import { Fragment, useEffect, useState } from "react";
import { localeTag, t } from "../../lib/i18n";
import { useLocale } from "../../lib/locale-context";
import { fullDateLabel, shortDateLabel, weekdayLabel, weekRangeLabel } from "../../lib/date-field";
import { api } from "../../lib/api";
import type { Lesson, Substitution, TimetableData } from "../../lib/types";
import { DateField } from "../date-field";
import { Icon } from "../icon";
import { Empty, Notice, PageTitle } from "../ui";

export function TimetableView() {
  const [day, setDay] = useState(new Date().toISOString().slice(0, 10)); const [mode, setMode] = useState<"week" | "day">("week"); const [data, setData] = useState<TimetableData | null>(null); const [substitutions, setSubstitutions] = useState<Substitution[]>([]); const [error, setError] = useState("");
  useEffect(() => { let live = true; Promise.all([api<TimetableData>(`/timetable/${mode}?day=${day}`), api<{ days: Substitution[] }>(`/substitutions/week?day=${day}`)]).then(([schedule, changes]) => { if (live) { setData(schedule); setSubstitutions(changes.days); setError(""); } }).catch((e: Error) => { if (live) setError(e.message); }); return () => { live = false; }; }, [day, mode]);
  function addDay(change: number) { const d = new Date(`${day}T12:00:00`); d.setDate(d.getDate() + change); setDay(d.toISOString().slice(0, 10)); }
  function periodRange(lesson: Lesson) { const numbers = (lesson.period.match(/\d+/g) ?? []).map(Number); return { first: numbers[0] ?? 0, last: numbers[1] ?? numbers[0] ?? 0 }; }
  const week = data?.days ?? [];
  const locale = localeTag();
  const weekHeading = week.length
    ? `${t("timetable.weekTab")} ${weekRangeLabel(week[0].date, week[week.length - 1].date, locale, data?.week_label ?? "")}`
    : t("nav.timetable");
  const dayHeading = fullDateLabel(day, locale, data?.day_label ?? t("nav.timetable"));
  const periods = Array.from(new Set(week.flatMap((item) => item.lessons.filter((lesson) => !lesson.is_event).flatMap((lesson) => { const range = periodRange(lesson); return range.first ? Array.from({ length: range.last - range.first + 1 }, (_, i) => range.first + i) : []; })))).sort((a, b) => a - b);
  const cells = new Map<string, Lesson>(); const covered = new Set<string>();
  for (const item of week) for (const lesson of item.lessons) { const range = periodRange(lesson); if (!range.first) continue; cells.set(`${item.date}-${range.first}`, lesson); for (let period = range.first + 1; period <= range.last; period++) covered.add(`${item.date}-${period}`); }
  const lessonCards = (items: Lesson[]) => items.map((lesson, index) => <article className={`lesson card${lesson.is_cancelled ? " is-cancelled" : ""}${lesson.is_event ? " is-event" : ""}`} key={`${lesson.period}-${index}`}><div className="lesson-time">{lesson.time}</div><div className="lesson-main"><h3>{lesson.title}</h3><div className="meta">{lesson.is_cancelled && <span className="tag tag-red">{t("overview.cancelled")}</span>}{lesson.is_event && <span className="tag tag-amber">{t("timetable.eventTag")}</span>}{lesson.is_online && <span className="tag tag-blue">{t("timetable.onlineTag")}</span>}{lesson.teachers && <span>{lesson.teachers}</span>}{lesson.rooms && <span>{t("overview.room", { rooms: lesson.rooms })}</span>}</div></div></article>);
  const substitutionAction = (action: string) => action === "remove" ? t("overview.cancelled") : action === "add" ? t("agenda.actionAdd") : t("agenda.actionChange");
  return <><PageTitle eyebrow={t("timetable.eyebrow")} title={mode === "week" ? weekHeading : dayHeading} detail={mode === "week" ? t("timetable.weekDetail", { count: week.reduce((total, item) => total + item.lessons.length, 0) }) : t("timetable.dayDetail", { count: (data?.lessons ?? []).length })} /><Notice error={error} />
    <div className="schedule-toolbar"><div className="view-toggle" role="tablist" aria-label={t("timetable.viewAria")}><button type="button" role="tab" aria-selected={mode === "day"} className={mode === "day" ? "active" : ""} onClick={() => setMode("day")}>{t("timetable.dayTab")}</button><button type="button" role="tab" aria-selected={mode === "week"} className={mode === "week" ? "active" : ""} onClick={() => setMode("week")}>{t("agenda.weekLabel")}</button></div>{mode === "day" ? <div className="day-nav"><button className="btn btn-light btn-sm" onClick={() => addDay(-1)}><Icon name="left" />{t("timetable.backDay")}</button><div className="field"><label htmlFor="timetable-day">{t("timetable.dayTab")}</label><DateField id="timetable-day" ariaLabel={t("timetable.dayLabel")} value={day} onChange={setDay} /></div><button className="btn btn-light btn-sm" onClick={() => setDay(new Date().toISOString().slice(0, 10))}><Icon name="calendar" />{t("overview.today")}</button><button className="btn btn-light btn-sm" onClick={() => addDay(1)}>{t("timetable.nextDay")}<Icon name="right" /></button></div> : <div className="day-nav"><button className="btn btn-light btn-sm" onClick={() => addDay(-7)}><Icon name="left" />{t("agenda.prevWeek")}</button><button className="btn btn-light btn-sm" onClick={() => setDay(new Date().toISOString().slice(0, 10))}>{t("agenda.thisWeek")}</button><button className="btn btn-light btn-sm" onClick={() => addDay(7)}>{t("agenda.nextWeek")}<Icon name="right" /></button></div>}</div>
    {mode === "week" ? <div className="tt-scroll"><div className="tt-matrix anim-in"><div style={{ gridColumn: 1, gridRow: 1 }} />{week.map((item, index) => <div className="tt-day" style={{ gridColumn: index + 2, gridRow: 1 }} key={item.date}>{weekdayLabel(item.date, localeTag(), item.day_name)}<small>{shortDateLabel(item.date, localeTag(), item.day_date)}</small>{item.is_today && <span className="tag tag-solid">{t("timetable.todayTag")}</span>}</div>)}{periods.map((period, index) => <Fragment key={period}><div className="tt-period" style={{ gridColumn: 1, gridRow: index + 2 }}>{period}.</div>{week.map((item, dayIndex) => { const lesson = cells.get(`${item.date}-${period}`); const range = lesson ? periodRange(lesson) : { first: period, last: period }; if (covered.has(`${item.date}-${period}`)) return null; return <div className={`tt-cell${lesson?.is_cancelled ? " is-cancelled" : ""}${lesson?.is_event ? " is-event" : ""}`} style={{ gridColumn: dayIndex + 2, gridRow: `${index + 2}${range.last > range.first ? ` / span ${range.last - range.first + 1}` : ""}` }} key={`${item.date}-${period}`}>{lesson ? <><strong>{lesson.title}</strong><small>{lesson.rooms ? t("overview.room", { rooms: lesson.rooms }) : ""}{lesson.rooms && lesson.teachers ? " · " : ""}{lesson.teachers}{lesson.time && !lesson.is_lernzeit && !lesson.is_event ? `${lesson.rooms || lesson.teachers ? " · " : ""}${lesson.time}` : ""}</small>{lesson.is_cancelled && <span className="tag tag-red">{t("timetable.cancelledSmall")}</span>}</> : <span className="tt-empty">–</span>}</div>; })}</Fragment>)}</div></div> : <div id="list">{lessonCards(data?.lessons ?? [])}{!data?.lessons?.length && <Empty>{t("timetable.emptyDay")}</Empty>}</div>}
    <section className="agenda-section timetable-substitutions"><h2>{t("agenda.subsTitle")}</h2>{substitutions.some((entry) => entry.changes.length) ? substitutions.map((entry) => entry.changes.map((change, index) => <div className="agenda-day" key={`${entry.date}-${index}`}><h3>{weekdayLabel(entry.date, localeTag(), entry.day_label)}</h3><article className="card agenda-change"><span className="agenda-period">{t("timetable.lessonHour", { lesson: change.lesson })}</span><div><strong>{change.title}</strong><p className="agenda-meta">{change.class ? t("agenda.classLabel", { cls: change.class }) : t("agenda.planChange")}</p></div><span className={`tag ${change.action === "remove" ? "tag-red" : change.action === "add" ? "tag-blue" : "tag-amber"}`}>{substitutionAction(change.action)}</span></article></div>)) : <div className="card agenda-empty">{t("agenda.emptySubs")}</div>}</section>
  </>;
}
